add main service v0.1 + clean code
Advaito/java-explore-with-me pull request #7
Opened 2023-06-12 23:47 UTC by Advaito

2023-06-15 21:16 UTC, Advaito commented
Привет) вообще идей нет как можно обкрутить это... никак не могу исправить эту ошибку! 
 2.  AssertionError  Значение поля views должно увеличится на 1 после выполнения GET запроса с уникального IP к событию                              
                     expected 3 to equal 1                                                                                                           
                     at assertion:2 in test-script                                                                                                   
                     inside "Validation / Event / Misc tests / Проверка работы поля views"

2023-06-16 21:43 UTC, ohelly requested changes
Привет! По поводу ошибки, при данном запросе(GET /events/{id}) в поле view должно возвращаться уникальное(по IP) значение просмотров. У тебя даже зашита такая возможность в код, но она игнорируется)
![image](https://github.com/Advaito/java-explore-with-me/assets/51891976/9e49060f-1348-45d3-b82e-b7030f8915a1)
Но тут нужно быть внимательным, так как просто поставить true в данном месте - неправильно, так как не во всех случаях просмотры должны быть уникальным.
После исправления смогу приступить к основной проверке и проверю как можно скорее, чтобы не задерживать. Удачи!

2023-06-17 18:04 UTC, Advaito commented
кучу логики попериписывал за сутки :D в итоге все вернул как есть

2023-06-17 18:09 UTC, ohelly approved these changes
Привет! Отличная работа, все работает корректно. Оставил несколько рекомендаций, особое внимание прошу уделить проблеме N + 1 запросов, это довольно часто встречается и часто спрашивают на собеседованиях. Работу принимаю, можно двигаться дальше!

2023-06-17 18:09 UTC, ohelly commented on main-service/src/main/java/ru/practicum/main_service/event/model/Request.java
> +    @ManyToOne(fetch = FetchType.LAZY)
FetchType = Lazy привовдит к  N + 1 проблеме и тип Eager ее также не решает. Для того чтобы решить данную проблему проще всего в репозиториях использовать join fetch.
https://habr.com/ru/companies/otus/articles/529692/
Join fetch не единственное решение, но в почти всегда хватает его.

2023-06-17 18:09 UTC, ohelly commented on main-service/src/main/java/ru/practicum/main_service/event/service/RequestServiceImpl.java
> +        if (oldRequest.isPresent()) {
Рекомендация: Вместо данного условия можно использовать метод .orElseThrow у опционала

2023-06-17 18:09 UTC, ohelly commented on pom.xml
> +			<dependency>
Рекомендация: Данную зависимость также будет лучше убрать

2023-06-21 21:31 UTC, merged